name: Build and Deploy Documentation

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build_docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Convert Markdown to XML
      run: |
        docker pull ghcr.io/karunamon/mmark:latest
        for i in `ls standards/GS*.md`; do
          base=$(basename $i)
          fname=$(echo $base | cut -d '.' -f 1)
          echo $fname
          docker run --rm -v $(pwd):/workdir ghcr.io/karunamon/mmark mmark /workdir/$i > $fname.xml
        done
      
    - name: Convert XML to RFC
      run: |
        mkdir work
        docker pull ghcr.io/karunamon/xml2rfc:latest
        for i in `ls *.xml`; do
          fname=$(echo $i | cut -d '.' -f 1)
          echo $fname
          docker run --rm -v $(pwd):/workdir ghcr.io/karunamon/xml2rfc xml2rfc --text /workdir/$i -o /workdir/work/$fname.txt
          docker run --rm -v $(pwd):/workdir ghcr.io/karunamon/xml2rfc xml2rfc --html /workdir/$i -o /workdir/work/$fname.html
        done

    - name: Copy to Server
      run: |
        scp -v work/* gametrics@rgbcast.com:public_html/standards/

    - name: Send Notification
      uses: Ilshidur/action-discord@master
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
        content: "Build and deployment succeeded"
