# This is a basic workflow to help you get started with Actions

name: XML2RFC Validation

on:
  pull_request:
    branches:  master
    paths:
      - 'grc.md'

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Golang
        uses: actions/setup-go@v2
        with:
          go-version: '1.11.6'
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.4'
      
      - name: Setup environment
        run: |
          echo "GOPATH=$(go env GOPATH)" >> $GITHUB_ENV
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
      
      - name: Install dependencies
        run: |
          pip3 install xml2rfc
          git clone https://github.com/mmarkdown/mmark.git
          cd mmark && go get && cd ..
          
      - name: Compile output page
        run: |
          mmark grc.md > grc.xml
          xml2rfc grc.xml --html
          mkdir public
          mv grc.html public/index.html
        
